package export

import (
	"path/filepath"
	"strings"
)

// WritePytest emits a fixture and a pytest module that replays the run's tool
// calls and asserts their contract holds and the findings did not recur.
// Returns the paths written, fixture first.
func WritePytest(dir string, fx Fixture) ([]string, error) {
	base := fixtureBase(fx)
	fixtureName := base + "_fixture.json"
	fixturePath := filepath.Join(dir, fixtureName)
	testPath := filepath.Join(dir, "test_"+base+".py")
	if err := ensureDir(dir); err != nil {
		return nil, err
	}
	if err := writeJSON(fixturePath, fx); err != nil {
		return nil, err
	}
	src := strings.ReplaceAll(pytestTemplate, "__FIXTURE__", fixtureName)
	if err := writeFile(testPath, src); err != nil {
		return nil, err
	}
	return []string{fixturePath, testPath}, nil
}

const pytestTemplate = `"""Regression test generated by capybara.

test_tool_contracts replays the recording and needs nothing but this file.
test_live_tool_contracts calls the tools themselves, so it only covers runs
the SDK traced, and it really does run their side effects.
"""

import importlib
import json
from pathlib import Path

import pytest

from capybara.replay import Session

_FIXTURE = json.loads(
    Path(__file__).with_name("__FIXTURE__").read_text(encoding="utf8")
)
_LIVE = [entry for entry in _FIXTURE["tools"] if entry.get("target")]


def _jtype(value):
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "boolean"
    if isinstance(value, (int, float)):
        return "number"
    if isinstance(value, str):
        return "string"
    if isinstance(value, list):
        return "array"
    return "object"


def _check_schema(value, schema, path="$"):
    types = schema.get("type") or []
    if isinstance(types, str):
        types = [types]
    if types and _jtype(value) not in types:
        raise AssertionError(f"{path}: type {_jtype(value)} not in {types}")
    for field in schema.get("required", []):
        assert isinstance(value, dict) and field in value, (
            f"{path}.{field}: required field missing"
        )
    for field, sub in (schema.get("properties") or {}).items():
        if isinstance(value, dict) and field in value:
            _check_schema(value[field], sub, f"{path}.{field}")
    items = schema.get("items")
    if items and isinstance(value, list):
        for index, element in enumerate(value):
            _check_schema(element, items, f"{path}[{index}]")


def _at(value, dotted):
    for key in dotted.split("."):
        if not isinstance(value, dict) or key not in value:
            return None, False
        value = value[key]
    return value, True


def _check_finding_gone(value, finding, tool):
    kind = finding["type"]
    if kind == "drift":
        for field in finding.get("missing", []):
            _, present = _at(value, field)
            assert present, f"{tool}: drift recurred, field {field} still missing"
        for retyped in finding.get("retyped", []):
            got, present = _at(value, retyped["field"])
            if present:
                assert _jtype(got) in retyped["want"].split("|"), (
                    f"{tool} {retyped['field']}: {_jtype(got)} not {retyped['want']}"
                )
    elif kind == "malformed":
        assert not isinstance(value, str), f"{tool}: malformed output recurred"
    elif kind == "empty_payload":
        assert value not in (None, "", {}, []), f"{tool}: empty payload recurred"


def _assert_contract(output, entry):
    _check_schema(output, entry["schema"])
    for finding in entry.get("findings", []):
        _check_finding_gone(output, finding, entry["tool"])


def test_tool_contracts():
    session = Session({"llm": [], "tools": _FIXTURE["tools"]})
    for entry in _FIXTURE["tools"]:
        _assert_contract(session.serve_tool(entry["tool"], entry["input"]), entry)


def _call(target, arguments):
    module, _, qualname = target.partition(":")
    tool = importlib.import_module(module)
    for part in qualname.split("."):
        tool = getattr(tool, part)
    result = tool(**json.loads(arguments))
    # Match how the recording was serialized, so both sides compare alike.
    return json.loads(json.dumps(result, default=str))


@pytest.mark.skipif(not _LIVE, reason="run carries no tool the SDK traced")
def test_live_tool_contracts():
    for entry in _LIVE:
        _assert_contract(_call(entry["target"], entry["input"]), entry)
`
