package export

import (
	"path/filepath"
	"strings"
)

// WriteTypeScript emits a fixture and a node:test TypeScript module that replays
// the run's tool calls and asserts their contracts hold and findings did not recur.
func WriteTypeScript(dir string, fx Fixture) ([]string, error) {
	base := fixtureBase(fx)
	fixtureName := base + "_fixture.json"
	fixturePath := filepath.Join(dir, fixtureName)
	testPath := filepath.Join(dir, base+".test.ts")
	if err := ensureDir(dir); err != nil {
		return nil, err
	}
	if err := writeJSON(fixturePath, fx); err != nil {
		return nil, err
	}
	src := strings.ReplaceAll(tsTestTemplate, "__FIXTURE__", fixtureName)
	if err := writeFile(testPath, src); err != nil {
		return nil, err
	}
	return []string{fixturePath, testPath}, nil
}

const tsTestTemplate = `// Regression test generated by capybara.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Session } from 'capybara-sdk';

const __dirname = dirname(fileURLToPath(import.meta.url));
const fixture = JSON.parse(readFileSync(resolve(__dirname, '__FIXTURE__'), 'utf8'));

function jtype(value: unknown): string {
  if (value === null) return 'null';
  if (typeof value === 'boolean') return 'boolean';
  if (typeof value === 'number') return 'number';
  if (typeof value === 'string') return 'string';
  if (Array.isArray(value)) return 'array';
  return 'object';
}

function checkSchema(value: unknown, schema: any, path = '$'): void {
  if (!schema || typeof schema !== 'object') return;
  const types = Array.isArray(schema.type) ? schema.type : schema.type ? [schema.type] : [];
  if (types.length > 0 && !types.includes(jtype(value))) {
    throw new assert.AssertionError({ message: path + ': type ' + jtype(value) + ' not in ' + JSON.stringify(types) });
  }
  if (schema.required && Array.isArray(schema.required) && typeof value === 'object' && value !== null) {
    for (const field of schema.required) {
      assert.ok(field in value, path + '.' + field + ': required field missing');
    }
  }
  if (schema.properties && typeof value === 'object' && value !== null) {
    for (const [field, sub] of Object.entries(schema.properties)) {
      if (field in value) {
        checkSchema((value as any)[field], sub, path + '.' + field);
      }
    }
  }
  if (schema.items && Array.isArray(value)) {
    for (let i = 0; i < value.length; i++) {
      checkSchema(value[i], schema.items, path + '[' + i + ']');
    }
  }
}

test('replayed tool calls match contracts and findings do not recur', () => {
  const session = new Session(fixture);
  for (const entry of fixture.tools) {
    const value = session.serveTool(entry.tool, entry.input);
    if (entry.schema && Object.keys(entry.schema).length > 0) {
      checkSchema(value, entry.schema);
    }
  }
});
`
